spring:
  application:
    name: hello-spring-cloud-service-provider
  zipkin:
    base-url: http://192.168.137.101:9411
  boot:
    admin:
      client:
        url: http://localhost:8084


server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#logging:
#  path: ./logs